services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    command: npm run start:dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/app
          ignore:
            - ./backend/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/app
          ignore:
            - ./frontend/node_modules
